[tool.poetry]
name = "trader-quickstart"
version = "0.1.0"
description = "A quickstart for the trader agent for AI prediction markets on Gnosis at https://github.com/valory-xyz/trader"
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>", "Ojuswi Rastogi <ojuswimail@gmail.com>"]
readme = "README.md"
package-mode = false
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-app.git", rev = "2e0e747b796f06cddd9fcbfc325a0d1db3f0a909", python = ">=3.9,<3.12" }

[tool.poetry.group.dev.dependencies]
pexpect = "^4.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
