name: Python Tests

on:
  push:
    branches:
      - feat/updating_test_script
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Explicitly setting Python 3.10
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry config installer.max-workers 10
        
    - name: Clear Poetry Cache and Lock File
      run: |
        rm -f poetry.lock || true
        poetry cache clear . --all || true
        
    - name: Install dependencies
      run: |
        poetry install --no-interaction
      
    - name: Run tests
      run: poetry run pytest -v tests/test_run_service.py -s --log-cli-level=INFO